#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HackAtHomeClient.Resource", IsApplication=true)]

namespace HackAtHomeClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int xamarin = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int button1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int editText1 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int editText2 = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int editTextEmail = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int editTextPassword = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int imageViewEvidence = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout1 = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout2 = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int listViewEvidence = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int textView1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int textView2 = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int textViewEvidence = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int textViewEvidenceStatus = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int textViewEvidenceTitle = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int textViewFullName = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int tvDetailDescription = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int tvDetailFullName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int tvDetailStatus = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int tvDetailTitle = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int webViewContent = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EvidenceDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EvidenceList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EvidenceListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int ButtonValidate = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int DescriptionText = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int EmailText = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int EvidenceText = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int PasswordText = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
